service: tc-lambda-slack-issue-app
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds:
      - ${ssm:/issue-reporting/vpc-security-group-id-1}
    subnetIds:
      - ${ssm:/issue-reporting/vpc-subnet-id-1}
  role: ${ssm:/issue-reporting/lambda-role}
  runtime: nodejs16.x
  memorySize: 256
  timeout: 15

custom:
  serverlessSsmFetch:
    SLACK_BOT_TOKEN: /issue-reporting/slack-bot-token
    SLACK_SIGNING_SECRET: /issue-reporting/slack-signing-secret
    GENIE_KEY: /issue-reporting/genie-key

functions:
  tc-lambda-slack-issue-app:
    handler: lambda.handler
    name: ${self:provider.stage}-tc-lambda-slack-issue-app
    events:
      - alb:
          listenerArn: ${ssm:/issue-reporting/alb-arn}
          priority: 151
          conditions:
            path: /v5/slack-issue-app/slack/events

plugins:
  - serverless-ssm-fetch
